version: '3'
 
services:
  web:
    restart: always
    env_file: .env
    build: 
      context: .
    ports:
      - 127.0.0.1:5000:5000
    working_dir: /usr/src/app
    command: gunicorn -w 2 -b :5000 app:app
    depends_on:
      - postgres
  postgres:
    restart: always
    image: postgres:latest
    env_file: .env